// <auto-generated />
using System;
using DevDates.DBModel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevDates.DBModel.Migrations
{
    [DbContext(typeof(DevDatesDbContext))]
    [Migration("20230617105701_AddedKey")]
    partial class AddedKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevDates.DBModel.Data.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Genders__3214EC07DA6BD736");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("DevDates.DBModel.Data.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Interest__3214EC07357635C6");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("DevDates.DBModel.Data.Models.Like", b =>
                {
                    b.Property<string>("LikerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LikedId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.HasKey("LikerId", "LikedId")
                        .HasName("PK__Likes__50BBFF3E916FCE5A");

                    b.HasIndex("LikedId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("DevDates.DBModel.Data.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ResourceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ResourceUri")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ResourceURI");

                    b.HasKey("Id")
                        .HasName("PK__Resource__3214EC071098848C");

                    b.HasIndex("ResourceTypeId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("DevDates.DBModel.Data.Models.ResourcesType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Resource__3214EC07FF85144A");

                    b.ToTable("ResourcesTypes");
                });

            modelBuilder.Entity("DevDates.DBModel.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bio")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC076D009CCD");

                    b.HasIndex("GenderId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DevDates.DBModel.Data.Models.UsersPreference", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.HasKey("UserId", "GenderId")
                        .HasName("PK__UsersPre__736A82D3B322C613");

                    b.HasIndex("GenderId");

                    b.ToTable("UsersPreferences");
                });

            modelBuilder.Entity("GendersResource", b =>
                {
                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("GenderId", "ResourceId")
                        .HasName("PK__GendersR__AAC9F1E186608F56");

                    b.HasIndex("ResourceId");

                    b.ToTable("GendersResources", (string)null);
                });

            modelBuilder.Entity("InterestsResource", b =>
                {
                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("InterestId", "ResourceId")
                        .HasName("PK__Interest__C46E34712581E9BE");

                    b.HasIndex("ResourceId");

                    b.ToTable("InterestsResources", (string)null);
                });

            modelBuilder.Entity("UsersInterest", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "InterestId")
                        .HasName("PK__UsersInt__7580FE8A3A3E6E5B");

                    b.HasIndex("InterestId");

                    b.ToTable("UsersInterests", (string)null);
                });

            modelBuilder.Entity("UsersResource", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ResourceId")
                        .HasName("PK__UsersRes__F365D45A2520B708");

                    b.HasIndex("ResourceId");

                    b.ToTable("UsersResources", (string)null);
                });

            modelBuilder.Entity("DevDates.DBModel.Data.Models.Like", b =>
                {
                    b.HasOne("DevDates.DBModel.Data.Models.User", "Liked")
                        .WithMany("LikeLikeds")
                        .HasForeignKey("LikedId")
                        .IsRequired()
                        .HasConstraintName("FK__Likes__LikedId__395884C4");

                    b.HasOne("DevDates.DBModel.Data.Models.User", "Liker")
                        .WithMany("LikeLikers")
                        .HasForeignKey("LikerId")
                        .IsRequired()
                        .HasConstraintName("FK__Likes__LikerId__3864608B");

                    b.Navigation("Liked");

                    b.Navigation("Liker");
                });

            modelBuilder.Entity("DevDates.DBModel.Data.Models.Resource", b =>
                {
                    b.HasOne("DevDates.DBModel.Data.Models.ResourcesType", "ResourceType")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceTypeId")
                        .HasConstraintName("FK__Resources__Resou__208CD6FA");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("DevDates.DBModel.Data.Models.User", b =>
                {
                    b.HasOne("DevDates.DBModel.Data.Models.Gender", "Gender")
                        .WithMany("Users")
                        .HasForeignKey("GenderId")
                        .HasConstraintName("FK__Users__GenderId__1BC821DD");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("DevDates.DBModel.Data.Models.UsersPreference", b =>
                {
                    b.HasOne("DevDates.DBModel.Data.Models.Gender", "Gender")
                        .WithMany("UsersPreferences")
                        .HasForeignKey("GenderId")
                        .IsRequired()
                        .HasConstraintName("FK__UsersPref__Gende__31B762FC");

                    b.HasOne("DevDates.DBModel.Data.Models.User", "User")
                        .WithMany("UsersPreferences")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UsersPref__UserI__30C33EC3");

                    b.Navigation("Gender");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GendersResource", b =>
                {
                    b.HasOne("DevDates.DBModel.Data.Models.Gender", null)
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .IsRequired()
                        .HasConstraintName("FK__GendersRe__Gende__2CF2ADDF");

                    b.HasOne("DevDates.DBModel.Data.Models.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .IsRequired()
                        .HasConstraintName("FK__GendersRe__Resou__2DE6D218");
                });

            modelBuilder.Entity("InterestsResource", b =>
                {
                    b.HasOne("DevDates.DBModel.Data.Models.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .IsRequired()
                        .HasConstraintName("FK__Interests__Inter__25518C17");

                    b.HasOne("DevDates.DBModel.Data.Models.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .IsRequired()
                        .HasConstraintName("FK__Interests__Resou__2645B050");
                });

            modelBuilder.Entity("UsersInterest", b =>
                {
                    b.HasOne("DevDates.DBModel.Data.Models.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .IsRequired()
                        .HasConstraintName("FK__UsersInte__Inter__3587F3E0");

                    b.HasOne("DevDates.DBModel.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UsersInte__UserI__3493CFA7");
                });

            modelBuilder.Entity("UsersResource", b =>
                {
                    b.HasOne("DevDates.DBModel.Data.Models.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .IsRequired()
                        .HasConstraintName("FK__UsersReso__Resou__2A164134");

                    b.HasOne("DevDates.DBModel.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UsersReso__UserI__29221CFB");
                });

            modelBuilder.Entity("DevDates.DBModel.Data.Models.Gender", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("UsersPreferences");
                });

            modelBuilder.Entity("DevDates.DBModel.Data.Models.ResourcesType", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("DevDates.DBModel.Data.Models.User", b =>
                {
                    b.Navigation("LikeLikeds");

                    b.Navigation("LikeLikers");

                    b.Navigation("UsersPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
